code improvements
- improved logging
- more resiliant code (*hopefully*)

diff --git a/bins/sparse_dd b/bins/sparse_dd
--- a/bins/sparse_dd
+++ b/bins/sparse_dd
@@ -15,19 +15,34 @@
 # along with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 
+SMLOG="/var/log/SMlog"
+
+function exec_cmd(){
+   local CMD="$1"
+   echo "sparse_dd[$$] $CMD" >> ${SMLOG}
+   ( eval "$CMD " ) 2>&1 | sed "~s,^,sparse_dd[$$]," >> ${SMLOG}
+   local RET="$?"
+   if [ "$RET" != "0" ];then
+      echo "sparse_dd[$$]: execution failed (returncode $RET)" >> ${SMLOG}
+      return $RET
+      #exit $RET
+   fi
+   return 0
+}
+
+echo "sparse_dd[$$] call: $0 $@">> /var/log/SMlog
+
 ARGC=$#  # Number of args, not counting $0
 i=1  # Used as argument index
 cmd=${!i}
-echo "sparse_dd call:">> /var/log/SMlog
-echo "$0 $@" >> /var/log/SMlog
 
-while [ $i -le $ARGC ];
+while [ "$i" -le "$ARGC" ];
 do
     case ${!i} in
         -src)
                         i=$((i+1))
                         if [ -n "${!i}" ]; then
-                        src=${!i}
+                        	 src=${!i}
                         fi
                         ;;
         -dest)
@@ -46,49 +61,56 @@ do
     i=$((i+1))
 done
 #rbdsrs=`xe sr-list type=rbd | grep uuid | awk '{print $5}'`
-aiorbdsrs=`xe pbd-list device-config='image-type: aio' | grep sr-uuid | awk '{print $4} END {if (!NR) print "~~~"}'`
+aiorbdsrs="`xe pbd-list device-config='image-type: aio' | grep sr-uuid | awk '{print $4} END {if (!NR) print "~~~"}'`"
 case "$src|$dst" in
     *$aiorbdsrs*)
-        if [ `echo $src|grep $rbdsrs` ]; then
-            src_sr_uuid=`echo $src | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $1}'`
-            src_vdi_uuid=`echo $src | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $2}'`
-            source=`rbd ls -l --pool RBD_XenStorage-$src_sr_uuid | awk '{print \$1}' | grep $src_vdi_uuid | egrep "SNAP-$src_vdi_uuid\$"`
+        echo "sparse_dd[$$] src >>>$src<<< or dst >>>$dst<<< is in >>>$aiorbdsrs<<< ">> ${SMLOG}
+        if ( echo "$src"|grep -q "$rbdsrs" ); then
+            src_sr_uuid="`echo $src | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $1}'`"
+            src_vdi_uuid="`echo $src | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $2}'`"
+            source="`rbd ls -l --pool RBD_XenStorage-$src_sr_uuid | awk '{print \$1}' | grep $src_vdi_uuid | egrep "SNAP-$src_vdi_uuid\$"`"
             if [ -z $source ]; then
-                source=`rbd ls -l --pool RBD_XenStorage-$src_sr_uuid | awk '{print \$1}' | grep $src_vdi_uuid | egrep "VHD-$src_vdi_uuid\$"`
+                source="`rbd ls -l --pool RBD_XenStorage-$src_sr_uuid | awk '{print \$1}' | grep $src_vdi_uuid | egrep "VHD-$src_vdi_uuid\$"`"
             fi
-            if [ `echo $dst| grep http` ]; then
-                if [ -z $base ]; then
-                    /usr/bin/rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | /usr/bin/rbd2nbd -m -p --nbd $dst --rbd - 2>/dev/null
+            if ( echo "$dst"| grep -q "http" ); then
+                if [ -z "$base" ]; then
+                    exec_cmd "/usr/bin/rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | /usr/bin/rbd2nbd -m -p --nbd $dst --rbd -"
                     exit $?
                 else
                     # Not implemented
+                    echo "sparse_dd[$$] not implemented export-diff-fromsnap dst/$dst" >> ${SMLOG}
                     #/usr/bin/rbd export-diff --from-snap $from_snap $to_export - 2>/dev/null | rbd2nbd -m -p --raw $dst_file_name --rbd - --uuid to_export_vdi_uid 2>/dev/null
                     exit 1
                 fi
             else
-                if [ -z $base ]; then
-                    /usr/bin/rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | /usr/bin/rbd2raw -m -p --raw $dst --rbd - --uuid $src_vdi_uuid 2>/dev/null
+                if [ -z "$base" ]; then
+                    exec_cmd "/usr/bin/rbd export-diff RBD_XenStorage-$src_sr_uuid/$source - 2>/dev/null | /usr/bin/rbd2raw -m -p --raw $dst --rbd - --uuid $src_vdi_uuid"
                     exit $?
                 else
                     # Not implemented
+                    echo "sparse_dd[$$] not implemented export-diff-fromsnap dst/$dst" >> ${SMLOG}
                     #/usr/bin/rbd export-diff --from-snap $from_snap $to_export - 2>/dev/null | rbd2raw -m -p --raw $dst_file_name --rbd - --uuid to_export_vdi_uid 2>/dev/null
                     exit 1
                 fi
             fi
-        elif [ `echo $dst|grep $rbdsrs` ]; then
+        elif ( echo "$dst"|grep -q "$rbdsrs" ); then
             #dst_sr_uuid=`echo $src | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $1}'`
             #dst_vdi_uuid=`echo $src | sed 's/\/dev\/sm\/backend\///g' | awk -F/ '{print $2}'`
-            if [ -z $base ]; then
+            if [ -z "$base" ]; then
                 #/usr/bin/vhd2rbd --vhd $src --rbd - 2>/dev/null | /usr/bin/rbd import-diff - RBD_XenStorage-$dst_sr_uuid/VHD-$dst_vdi_uuid 2>/dev/null
+                echo "sparse_dd[$$] : /usr/libexec/xapi/sparse_dd-orig \"$@\"" >> ${SMLOG}
                 IFS=""
                 /usr/libexec/xapi/sparse_dd-orig "$@"
             else
+                echo "sparse_dd[$$] : /usr/libexec/xapi/sparse_dd-orig \"$@\"" >> ${SMLOG}
                 IFS=""
                 /usr/libexec/xapi/sparse_dd-orig "$@"
             fi
         fi
         ;;
     *)
+        echo "sparse_dd[$$] src >>>$src<<< or dst >>>$dst<<< is not(!) in >>>$aiorbdsrs<<< ">> ${SMLOG}
+        echo "sparse_dd[$$] : /usr/libexec/xapi/sparse_dd-orig \"$@\"" >> ${SMLOG}
         IFS=""
         /usr/libexec/xapi/sparse_dd-orig "$@"
         ;;
